export const CLOUD_RPC_ERROR_MESSAGES = Object.freeze({
  AUTH_REQUIRED: 'Entre na sua conta para continuar.',
  JOIN_CODE_INVALID: 'O código do convite é inválido.',
  JOIN_CODE_NOT_FOUND: 'Não encontramos um encontro com esse código.',
  JOIN_CODE_ROTATE_FORBIDDEN: 'Só o organizador pode trocar o código do encontro.',
  MATCH_NOT_FOUND: 'Partida não encontrada.',
  SCORE_FORBIDDEN: 'Você não pode registrar placar neste encontro.',
  SCORE_CLEAR_FORBIDDEN: 'Só o organizador pode limpar o placar.',
  SCORE_PARTIAL: 'Preencha os dois lados do placar.',
  SCORE_NEGATIVE: 'O placar deve usar números inteiros não negativos.',
  SCORE_TIE: 'O jogo não pode terminar empatado.',
  SCORE_VERSION_CONFLICT: 'Este placar foi alterado em outro dispositivo. Atualizamos os dados para você.',
  USE_SET_MATCH_SCORE: 'O placar só pode ser gravado pela função de atualização.',
  USE_LINK_PLAYER: 'Vincule o jogador pela função de perfil.',
  PLAYER_NOT_FOUND: 'Jogador não encontrado.',
  PLAYER_ALREADY_LINKED: 'Este jogador já está vinculado a uma conta.',
  USER_ALREADY_LINKED: 'Sua conta já está vinculada a outro jogador.',
  PLAYER_LINK_REQUIRES_OWNERSHIP: 'Só é possível vincular um jogador que você criou.',
  STRUCTURE_VERSION_CONFLICT: 'O encontro mudou em outro dispositivo. Recarregue e tente de novo.',
  STRUCTURE_FORBIDDEN: 'Você não pode alterar a estrutura deste encontro.',
  SESSION_FINISHED: 'Este encontro já está finalizado.',
  SESSION_NOT_DRAFT: 'Só é possível alterar o elenco em um encontro em rascunho.',
  SESSION_NOT_IN_PROGRESS: 'Esta operação só vale para encontro em andamento.',
  TEAMS_LOCKED: 'Os times não podem ser alterados depois que as rodadas existem.',
  PLAYER_NOT_IN_SESSION: 'O jogador precisa estar no elenco do encontro.',
  FINALIZE_NO_MATCHES: 'Não há partidas para finalizar.',
  FINALIZE_INCOMPLETE: 'Todos os jogos precisam ter placar antes de finalizar.',
  SESSION_NOT_FOUND: 'Encontro não encontrado.',
  INVALID_PLAN: 'O plano do encontro é inválido.',
  PLAYER_ARCHIVED: 'Este jogador está arquivado.',
  PLAYER_IN_TEAM: 'Remova o jogador dos times antes de tirá-lo do encontro.',
  USE_STRUCTURE_RPC: 'A estrutura do encontro só pode ser gravada pela função correspondente.',
  STATUS_IMMUTABLE: 'O status do encontro só muda pelas funções de rodada e finalização.',
  PLAYER_NOT_LINKED: 'Sua conta ainda não está associada a um jogador.',
  PLAYER_NAME_REQUIRED: 'Informe um nome para criar o jogador.',
  PLAYER_CLAIM_NOT_VISIBLE: 'Você só pode reivindicar um jogador de um encontro que compartilha.',
  PLAYER_CLAIM_DUPLICATE: 'Já existe um pedido de vínculo pendente.',
  PLAYER_CLAIM_FORBIDDEN: 'Só quem criou o jogador pode decidir o pedido.',
  PLAYER_CLAIM_NOT_FOUND: 'Pedido de vínculo não encontrado.',
  PLAYER_CLAIM_NOT_PENDING: 'Este pedido já foi decidido.',
  GROUP_NAME_REQUIRED: 'Informe um nome para o grupo.',
  GROUP_NOT_FOUND: 'Grupo não encontrado.',
  GROUP_JOIN_CODE_NOT_FOUND: 'Não encontramos um grupo com esse código.',
  GROUP_JOIN_CODE_ROTATE_FORBIDDEN: 'Só o organizador ou um admin pode trocar o código do grupo.',
  GROUP_JOIN_CODE_ROTATE_REQUIRED: 'O código do grupo só muda pela função de convite.',
  GROUP_FORBIDDEN: 'Você não pode alterar este grupo.',
  GROUP_ROLE_INVALID: 'Papel de grupo inválido.',
  GROUP_ROLE_FORBIDDEN: 'Você não pode alterar esse papel.',
  GROUP_OWNER_IMMUTABLE: 'O organizador do grupo não pode ser alterado nesta etapa.',
  GROUP_LAST_OWNER: 'O grupo precisa continuar com um organizador.',
  GROUP_MEMBER_NOT_FOUND: 'Essa pessoa não pertence ao grupo.',
  GROUP_ID_IMMUTABLE: 'O encontro não pode mudar de grupo depois de criado.',
  GROUP_ACCESS_DENIED: 'Você não participa deste grupo.',
  JOIN_CODE_GENERATION_FAILED: 'Não foi possível gerar um código de convite. Tente de novo.',
  COMPETITION_NOT_FOUND: 'Competição não encontrada.',
  COMPETITION_JOIN_CODE_NOT_FOUND: 'Não encontramos uma competição com esse código.',
  COMPETITION_JOIN_CODE_ROTATE_FORBIDDEN: 'Só o organizador ou um admin pode trocar o código da competição.',
  COMPETITION_JOIN_CODE_ROTATE_REQUIRED: 'O código da competição só muda pela função de convite.',
  COMPETITION_FORBIDDEN: 'Você não pode alterar esta competição.',
  COMPETITION_STRUCTURE_VERSION_CONFLICT:
    'A competição mudou em outro dispositivo. Recarregue e tente de novo.',
  COMPETITION_FINISHED: 'Esta competição já está finalizada.',
  COMPETITION_STATUS_FORBIDDEN: 'O status da competição só muda pelo fluxo de chave e finalização.',
  COMPETITION_NOT_DRAFT: 'Só é possível alterar os times no rascunho.',
  COMPETITION_TEAMS_LOCKED: 'Os times não podem ser alterados depois que a chave existe.',
  COMPETITION_MATCH_NOT_FOUND: 'Partida da competição não encontrada.',
  COMPETITION_MATCH_TEAMS_UNRESOLVED: 'A partida ainda não tem os dois times definidos.',
  COMPETITION_MATCH_HISTORY_LOCKED:
    'Não é possível alterar o histórico de uma partida por este fluxo. Limpe o placar dela primeiro.',
  COMPETITION_SCORE_IMMUTABLE: 'O placar só pode ser gravado pela função de atualização de placar.',
  COMPETITION_MATCH_HAS_HISTORY: 'Não é possível remover uma partida que já tem placar ou histórico.',
  COMPETITION_ROLE_INVALID: 'Papel da competição inválido.',
  COMPETITION_ROLE_FORBIDDEN: 'Você não pode alterar esse papel.',
  COMPETITION_OWNER_IMMUTABLE: 'O organizador da competição não pode ser alterado nesta etapa.',
  COMPETITION_MEMBER_NOT_FOUND: 'Essa pessoa não participa desta competição.',
  COMPETITION_ACCESS_DENIED: 'Você não participa desta competição.',
  INVALID_LEGACY_DATA: 'Os dados legados são inválidos e não podem ser importados.',
  UNSUPPORTED_SCHEMA: 'Esta versão do documento legado não é suportada.',
  NEEDS_PLAYER_MAPPING: 'Associe ou crie o jogador cloud antes de importar este item.',
  LEGACY_ID_CONFLICT: 'Este item legado já existe no cloud com outro dono.',
  CLOUD_ID_CONFLICT: 'Há um conflito de identificador com um registro cloud existente.',
  PLAYER_MAPPING_CONFLICT: 'Este jogador legado já está associado a outro player cloud.',
  PLAYER_MAPPING_INVALID: 'Não é possível associar a este player cloud.',
  LEGACY_IMPORT_BATCH_NOT_FOUND: 'Lote de importação não encontrado.',
  LEGACY_IMPORT_BATCH_INVALID: 'Este lote de importação não pode ser usado.',
  IMPORT_FAILED: 'A importação deste item falhou.',
  USERNAME_INVALID: 'O username deve ter 3 a 24 caracteres: letras minúsculas, números ou _.',
  USERNAME_TAKEN: 'Este username já está em uso.',
  USERNAME_ALLOCATION_FAILED: 'Não foi possível gerar um username. Tente de novo.',
  AVATAR_PATH_INVALID: 'A foto de perfil é inválida.',
  PROFILE_NOT_FOUND: 'Perfil não encontrado.',
  SOCIAL_PROFILE_UNAVAILABLE: 'Este jogador não tem perfil social.',
  FRIEND_SELF: 'Você não pode enviar pedido de amizade para si.',
  FRIEND_NOT_FOUND: 'Não encontramos esse usuário.',
  FRIEND_ALREADY: 'Vocês já são amigos.',
  FRIEND_REQUEST_PENDING: 'Já existe um pedido de amizade pendente.',
  FRIEND_REQUEST_NOT_FOUND: 'Pedido de amizade não encontrado.',
  FRIEND_REQUEST_FORBIDDEN: 'Você não pode alterar este pedido de amizade.',
  FRIEND_REQUEST_NOT_PENDING: 'Este pedido já foi decidido.',
  FRIENDSHIP_NOT_FOUND: 'Amizade não encontrada.',
  GROUP_MESSAGE_INVALID: 'A mensagem precisa ter entre 1 e 500 caracteres.',
  GROUP_MESSAGE_NOT_FOUND: 'Mensagem não encontrada.',
  GROUP_MESSAGE_FORBIDDEN: 'Você só pode editar ou apagar a própria mensagem.',
  GROUP_MESSAGE_DELETED: 'Esta mensagem já foi removida.',
  GROUP_MESSAGE_IMMUTABLE: 'Não é possível alterar o remetente desta mensagem.',
});

export function rpcErrorCode(error) {
  const message = String(error?.message ?? error ?? '');
  const codes = Object.keys(CLOUD_RPC_ERROR_MESSAGES).sort((left, right) => right.length - left.length);
  const match = message.match(new RegExp(`(${codes.join('|')})`));
  return match?.[1] ?? null;
}

export function messageForCloudError(error) {
  const code = typeof error === 'string' ? error : rpcErrorCode(error) ?? error?.code;
  return CLOUD_RPC_ERROR_MESSAGES[code] ?? error?.message ?? 'Não foi possível concluir a operação.';
}
